[package]
name = "pgfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
# pprof = { version = "0.1.0", path = "../pprof" }

[dev-dependencies]
rand = "0.8.5"
