[package]
name = "pgfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
rusttype = "0.9.2"
sdl2 = { version = "0.35.2", features = ["unsafe_textures", "mixer"] }
stb_image = "0.2.4"
miniaudio = "0.10.0"

[dev-dependencies]
rand = "0.8.5"
